In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_feather('../data/h201.feather')
deps = pd.read_csv('../data/Health Status Variables.csv')

In [4]:
df.loc[df['AGELAST'] <= 17]

,DUID,PID,DUPERSID,PANEL,FAMID31,FAMID42,FAMID53,FAMID17,FAMIDYR,CPSFAMID,...,RXPTR17,RXOTH17,PERWT17F,FAMWT17F,FAMWT17C,SAQWT17F,DIABW17F,CSAQW17F,VARSTR,VARPSU
2,10001.0,103.0,10001103,21.0,A,A,A,A,A,A,...,135.0,0.0,12308.918980,13651.501535,13651.501535,0.0,0.0,0.0,1021.0,1.0
3,10001.0,104.0,10001104,21.0,A,A,A,A,A,A,...,0.0,0.0,12280.755977,13651.501535,13651.501535,0.0,0.0,0.0,1021.0,1.0
9,10005.0,103.0,10005103,21.0,A,A,A,A,A,A,...,0.0,0.0,6815.521393,5474.354296,5474.354296,0.0,0.0,0.0,1012.0,2.0
13,10008.0,104.0,10008104,21.0,A,A,A,A,A,A,...,0.0,0.0,10499.096975,0.000000,0.000000,0.0,0.0,0.0,1142.0,1.0
14,10008.0,105.0,10008105,21.0,A,A,A,A,A,A,...,0.0,0.0,12976.631062,0.000000,0.000000,0.0,0.0,0.0,1142.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31871,99691.0,103.0,99691103,22.0,A,A,A,A,A,A,...,0.0,0.0,3921.265452,4005.681854,4005.681854,0.0,0.0,0.0,2043.0,1.0
31873,99691.0,105.0,99691105,22.0,A,A,A,A,A,A,...,0.0,0.0,4624.282987,4005.681854,4005.681854,0.0,0.0,0.0,2043.0,1.0
31874,99691.0,106.0,99691106,22.0,A,A,A,A,A,A,...,0.0,0.0,4789.151346,4005.681854,4005.681854,0.0,0.0,0.0,2043.0,1.0
31878,99692.0,103.0,99692103,22.0,A,A,A,A,A,A,...,0.0,0.0,6860.477839,6341.328544,6341.328544,0.0,0.0,0.0,2008.0,2.0
31879,99692.0,104.0,99692104,22.0,A,A,A,A,A,A,...,24.0,0.0,7735.807822,6341.328544,6341.328544,0.0,0.0,0.0,2008.0,2.0

In [5]:
our_vars = [col for col in deps['VARIABLE'][30:97]]
our_vars.append('AGELAST')

In [6]:
our_df = df.loc[(df['AGELAST'] <= 17) & (df['AGELAST'] >= 5), our_vars]

In [10]:
our_df = our_df.loc[(our_df['UNHAP42'] >= 0) & (our_df['UNHAP42'] <= 4), :]

In [11]:
our_df['UNHAP42'] = our_df['UNHAP42'].map({0:0, 1:1, 2:1, 3:1, 4:1})

<ipython-input-11-23c42f9c2225>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  our_df['UNHAP42'] = our_df['UNHAP42'].map({0:0, 1:1, 2:1, 3:1, 4:1})

In [13]:
our_df['UNHAP42'].value_counts(normalize=True)

0    0.736149
1    0.263851
Name: UNHAP42, dtype: float64

In [17]:
our_df.to_csv('../data/semi_clean_df.csv', index=False)