In [1]:
# Imports libraries 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import missingno as msno
import statsmodels.api as sm
from statsmodels.formula.api import ols

#sklearn imports
from sklearn.linear_model import LinearRegression, Ridge, Lasso, RidgeCV, LassoCV
from sklearn.model_selection import train_test_split, cross_val_score, cross_validate
from sklearn.metrics import mean_squared_error, r2_score

from sklearn.impute import SimpleImputer 
from sklearn.preprocessing import StandardScaler, PolynomialFeatures 

import patsy
%matplotlib inline
# y, X = patsy.dmatrices(formula, data=diamonds, return_type='dataframe')

In [2]:
# Import clean train data
df = pd.read_csv('./data/train_clean.csv')
df

,Id,PID,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,...,Veenker,YearBuilt_squ,Hip,Other_roof,BsmtFinType1*BsmtFinSF1,BsmtFinType2*BsmtFinSF2,ln_1stFlrSF,HeatingQC*CentralAir,TotalBsmtSF*BsmtUnfSF,BedroomAbvGr*FullBath
0,109,533352170,60,RL,NaN,13517,Pave,NaN,IR1,Lvl,...,0,3904576,0,0,3198.0,0.0,6.586172,5,139200.0,6
1,544,531379050,60,RL,43.0,11492,Pave,NaN,IR1,Lvl,...,0,3984016,0,0,3822.0,0.0,6.816736,5,251988.0,8
2,153,535304180,20,RL,68.0,7922,Pave,NaN,Reg,Lvl,...,0,3814209,0,0,4386.0,0.0,6.963190,3,344582.0,3
3,318,916386060,60,RL,73.0,9802,Pave,NaN,Reg,Lvl,...,0,4024036,0,0,0.0,0.0,6.612041,4,147456.0,6
4,255,906425045,50,RL,82.0,14235,Pave,NaN,IR1,Lvl,...,0,3610000,0,0,0.0,0.0,6.722630,3,456976.0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2046,1587,921126030,20,RL,79.0,11449,Pave,NaN,IR1,HLS,...,0,4028049,0,0,6066.0,0.0,7.454720,5,1644732.0,6
2047,785,905377130,30,RL,NaN,12342,Pave,NaN,IR1,Lvl,...,0,3763600,0,0,1048.0,0.0,6.758095,5,515739.0,1
2048,916,909253010,50,RL,57.0,7558,Pave,NaN,Reg,Bnk,...,0,3717184,0,0,0.0,0.0,7.066467,4,802816.0,3
2049,639,535179160,20,RL,80.0,10400,Pave,NaN,Reg,Lvl,...,0,3825936,0,0,465.0,1500.0,7.090077,3,354000.0,3
2050,10,527162130,60,RL,60.0,7500,Pave,NaN,Reg,Lvl,...,0,3996001,0,0,0.0,0.0,6.935370,4,988036.0,6

## Linear Regression Model

## Create our features matrix (`X`) and target vector (`y`)

In [3]:
# formula = 'SalePrice ~ ln_LotArea + ln_GrLivArea + GarageArea + OverallQual + TotalBsmtSF'
#  + GarageCars

In [4]:
df.columns

Index(['Id', 'PID', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea',
       'Street', 'Alley', 'LotShape', 'LandContour',
       ...
       'Veenker', 'YearBuilt_squ', 'Hip', 'Other_roof',
       'BsmtFinType1*BsmtFinSF1', 'BsmtFinType2*BsmtFinSF2', 'ln_1stFlrSF',
       'HeatingQC*CentralAir', 'TotalBsmtSF*BsmtUnfSF',
       'BedroomAbvGr*FullBath'],
      dtype='object', length=117)

In [28]:
# Instantiates the X and y variables
X = df[['ln_LotArea',
 'ln_GrLivArea',
 'GarageArea',
 'OverallQual',
 'TotalBsmtSF',
 'BrDale',
 'BrkSide',
 'ClearCr',
 'CollgCr',
 'Crawfor',
 'Edwards',
 'Gilbert',
 'IDOTRR',
 'MeadowV',
 'Mitchel',
 'NAmes',
 'NPkVill',
 'NWAmes',
 'NoRidge',
 'NridgHt',
 'OldTown',
 'Other_nhood',
 'SWISU',
 'Sawyer',
 'SawyerW',
 'Somerst',
 'StoneBr',
 'Timber',
 'Veenker',
 'YearBuilt_squ',
 'YearRemod-Built',
 'ExterQual',
 'BsmtQual',
 'BsmtFinType1',
 'BsmtFinSF1',
 'BsmtFinType1*BsmtFinSF1',
 '1stFlrSF',
 'HeatingQC',
 'BsmtFinType2',
 'BsmtFinSF2',
 'BsmtFinType2*BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF*BsmtUnfSF',
 'KitchenQual',
 'BedroomAbvGr',
 'FullBath',
 'BedroomAbvGr*FullBath',
 'Fireplaces',
 'FireplaceQu',
 'Hip',
 'Other_roof']]
y = df['SalePrice']


# y, X = patsy.dmatrices(formula, data=df, return_type='dataframe')
# X.drop(columns='Intercept', inplace=True)
# y = y.squeeze()

In [6]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2051 entries, 0 to 2050
Data columns (total 51 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ln_LotArea               2051 non-null   float64
 1   ln_GrLivArea             2051 non-null   float64
 2   GarageArea               2051 non-null   float64
 3   OverallQual              2051 non-null   int64
 4   TotalBsmtSF              2051 non-null   float64
 5   BrDale                   2051 non-null   int64
 6   BrkSide                  2051 non-null   int64
 7   ClearCr                  2051 non-null   int64
 8   CollgCr                  2051 non-null   int64
 9   Crawfor                  2051 non-null   int64
 10  Edwards                  2051 non-null   int64
 11  Gilbert                  2051 non-null   int64
 12  IDOTRR                   2051 non-null   int64
 13  MeadowV                  2051 non-null   int64
 14  Mitchel                  2051 non-null   int64
 15  NAmes                    2051 non-null   int64
 16  NPkVill                  2051 non-null   int64
 17  NWAmes                   2051 non-null   int64
 18  NoRidge                  2051 non-null   int64
 19  NridgHt                  2051 non-null   int64
 20  OldTown                  2051 non-null   int64
 21  Other_nhood              2051 non-null   int64
 22  SWISU                    2051 non-null   int64
 23  Sawyer                   2051 non-null   int64
 24  SawyerW                  2051 non-null   int64
 25  Somerst                  2051 non-null   int64
 26  StoneBr                  2051 non-null   int64
 27  Timber                   2051 non-null   int64
 28  Veenker                  2051 non-null   int64
 29  YearBuilt_squ            2051 non-null   int64
 30  YearRemod-Built          2051 non-null   int64
 31  ExterQual                2051 non-null   int64
 32  BsmtQual                 2051 non-null   int64
 33  BsmtFinType1             2051 non-null   int64
 34  BsmtFinSF1               2051 non-null   float64
 35  BsmtFinType1*BsmtFinSF1  2051 non-null   float64
 36  1stFlrSF                 2051 non-null   int64
 37  HeatingQC                2051 non-null   int64
 38  BsmtFinType2             2051 non-null   int64
 39  BsmtFinSF2               2051 non-null   float64
 40  BsmtFinType2*BsmtFinSF2  2051 non-null   float64
 41  BsmtUnfSF                2051 non-null   float64
 42  TotalBsmtSF*BsmtUnfSF    2051 non-null   float64
 43  KitchenQual              2051 non-null   int64
 44  BedroomAbvGr             2051 non-null   int64
 45  FullBath                 2051 non-null   int64
 46  BedroomAbvGr*FullBath    2051 non-null   int64
 47  Fireplaces               2051 non-null   int64
 48  FireplaceQu              2051 non-null   int64
 49  Hip                      2051 non-null   int64
 50  Other_roof               2051 non-null   int64
dtypes: float64(10), int64(41)
memory usage: 817.3 KB

In [8]:
# Creates the train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [9]:
X_train.head()

,ln_LotArea,ln_GrLivArea,GarageArea,OverallQual,TotalBsmtSF,BrDale,BrkSide,ClearCr,CollgCr,Crawfor,...,BsmtUnfSF,TotalBsmtSF*BsmtUnfSF,KitchenQual,BedroomAbvGr,FullBath,BedroomAbvGr*FullBath,Fireplaces,FireplaceQu,Hip,Other_roof
1591,8.881836,6.977281,379.0,5,808.0,0,0,0,0,0,...,808.0,652864.0,3,2,1,2,2,4,0,0
1199,9.584384,7.395722,808.0,8,1616.0,0,0,0,0,0,...,316.0,510656.0,4,3,2,6,1,4,1,0
827,9.512369,6.840547,288.0,5,935.0,0,0,0,0,0,...,0.0,0.0,3,3,1,3,0,0,1,0
1732,9.421411,7.897296,864.0,9,1365.0,0,0,0,0,0,...,379.0,517335.0,5,3,2,6,1,4,0,0
981,9.075322,7.399398,440.0,6,1065.0,0,1,0,0,0,...,765.0,814725.0,3,3,1,3,1,4,0,0

In [10]:
y_train.head()

1591    130000
1199    270000
827     137000
1732    398800
981     210000
Name: SalePrice, dtype: int64

In [11]:
# Functions to create statistical output
def stat_outputs(X, y):
    """Given a matrix X, and vector y, performs Ordinary Least Squares/Linear Regression using the
    statsmodel library and outputs the fitted model where attributes 
    of statsmodels can be called"""
    import statsmodels.api as sm
    X = X
    X = sm.add_constant(X, prepend=True)
    y = y
    
    lr_model = sm.OLS(y, X).fit()
    return lr_model  

# Function to output linear model metrics
def lin_metrics(model_fit, X, y):
    """Prints the model's r2_score, adj_r2, rmse, mse, and 
    cross val score given afitted model, a matrix X, and a vector y"""
    y_preds = model_fit.predict(X)
    
    r2 = r2_score(y, y_preds)
    cross_val = cross_val_score(model_fit, X, y, cv=10).mean()
    rmse = np.sqrt(mean_squared_error(y, y_preds))
    mse = mean_squared_error(y, y_preds)
    adj_r2 = 1 - (1-r2)*(len(y)-1)/(len(y)-X.shape[1]-1)
    
    print(f'r2_score = {r2}')
    print('=====================')
    print(f'cross_val_score = {cross_val}')
    print('=====================')
    print(f'RMSE = {rmse}')
    print('=====================')
    print(f'MSE = {mse}')
    print('=====================')
    print(f'adj_r2 = {adj_r2}')

In [12]:
# X_train

In [13]:
# Instantiates the linear regression model and fits the model to the train dataset
lm = LinearRegression()
lm.fit(X_train, y_train)

LinearRegression()

In [14]:
# prints the r2 score of the train dataset 
lm.score(X_train, y_train)

0.8598959330363204

In [15]:
# prints the cross validation r2 score of the training data
cross_val_score(lm, X_train, y_train).mean()

0.8414242359255478

In [16]:
# prints the r2 score of the test dataset
lm.score(X_test, y_test)

0.8821246609820645

In [17]:
X.columns

Index(['ln_LotArea', 'ln_GrLivArea', 'GarageArea', 'OverallQual',
       'TotalBsmtSF', 'BrDale', 'BrkSide', 'ClearCr', 'CollgCr', 'Crawfor',
       'Edwards', 'Gilbert', 'IDOTRR', 'MeadowV', 'Mitchel', 'NAmes',
       'NPkVill', 'NWAmes', 'NoRidge', 'NridgHt', 'OldTown', 'Other_nhood',
       'SWISU', 'Sawyer', 'SawyerW', 'Somerst', 'StoneBr', 'Timber', 'Veenker',
       'YearBuilt_squ', 'YearRemod-Built', 'ExterQual', 'BsmtQual',
       'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType1*BsmtFinSF1', '1stFlrSF',
       'HeatingQC', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtFinType2*BsmtFinSF2',
       'BsmtUnfSF', 'TotalBsmtSF*BsmtUnfSF', 'KitchenQual', 'BedroomAbvGr',
       'FullBath', 'BedroomAbvGr*FullBath', 'Fireplaces', 'FireplaceQu', 'Hip',
       'Other_roof'],
      dtype='object')

In [18]:
# formula = 'SalePrice ~ ' + (' + ').join(list(X.columns))
# statistics(formula, X_train, y_train).summary()

In [19]:
# Gets the statistical output of model using a self-defined function and statsmodels
stat_outputs(X_train, y_train).summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              SalePrice   R-squared:                       0.860
Model:                            OLS   Adj. R-squared:                  0.855
Method:                 Least Squares   F-statistic:                     178.8
Date:                Fri, 19 Mar 2021   Prob (F-statistic):               0.00
Time:                        21:06:53   Log-Likelihood:                -18040.
No. Observations:                1538   AIC:                         3.618e+04
Df Residuals:                    1486   BIC:                         3.646e+04
Df Model:                          51
Covariance Type:            nonrobust
===========================================================================================
                              coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                   -8.428e+05   9.16e+04     -9.203      0.000   -1.02e+06   -6.63e+05
ln_LotArea               2.725e+04   2490.582     10.943      0.000    2.24e+04    3.21e+04
ln_GrLivArea             5.061e+04   5249.252      9.642      0.000    4.03e+04    6.09e+04
GarageArea                 20.8106      5.349      3.891      0.000      10.318      31.303
OverallQual              1.071e+04   1133.630      9.448      0.000    8487.370    1.29e+04
TotalBsmtSF                33.0951    206.109      0.161      0.872    -371.201     437.391
BrDale                   2578.5599   1.11e+04      0.233      0.816   -1.92e+04    2.43e+04
BrkSide                 -4093.6290   9475.210     -0.432      0.666   -2.27e+04    1.45e+04
ClearCr                 -8201.0581   1.12e+04     -0.729      0.466   -3.03e+04    1.39e+04
CollgCr                 -1.833e+04   8272.728     -2.216      0.027   -3.46e+04   -2105.748
Crawfor                  1765.4792   9242.269      0.191      0.849   -1.64e+04    1.99e+04
Edwards                 -2.376e+04   8864.413     -2.680      0.007   -4.11e+04   -6370.690
Gilbert                 -2.298e+04   8631.907     -2.662      0.008   -3.99e+04   -6043.004
IDOTRR                  -1.911e+04   9918.564     -1.927      0.054   -3.86e+04     346.574
MeadowV                  1406.0138   1.06e+04      0.133      0.894   -1.93e+04    2.21e+04
Mitchel                 -1.651e+04   8963.442     -1.841      0.066   -3.41e+04    1077.249
NAmes                   -1.484e+04   8490.235     -1.747      0.081   -3.15e+04    1817.845
NPkVill                 -2042.1089   1.21e+04     -0.169      0.866   -2.58e+04    2.17e+04
NWAmes                  -1.736e+04   8886.294     -1.953      0.051   -3.48e+04      73.012
NoRidge                  2.704e+04   9537.901      2.835      0.005    8326.338    4.57e+04
NridgHt                  3.599e+04   8378.634      4.295      0.000    1.96e+04    5.24e+04
OldTown                 -1.946e+04   9277.182     -2.098      0.036   -3.77e+04   -1266.494
Other_nhood               764.0270    1.2e+04      0.064      0.949   -2.27e+04    2.43e+04
SWISU                   -1.179e+04   1.06e+04     -1.111      0.267   -3.26e+04    9026.364
Sawyer                  -1.913e+04   8935.727     -2.140      0.032   -3.67e+04   -1597.314
SawyerW                 -2.827e+04   8836.088     -3.200      0.001   -4.56e+04   -1.09e+04
Somerst                 -2140.9684   8094.002     -0.265      0.791    -1.8e+04    1.37e+04
StoneBr                  5.044e+04   9467.223      5.327      0.000    3.19e+04     6.9e+04
Timber                  -1.446e+04   9447.574     -1.530      0.126    -3.3e+04    4076.721
Veenker                 -1.377e+04   1.15e+04     -1.193      0.233   -3.64e+04    8874.937
YearBuilt_squ               0.0667      0.021      3.192      0.001       0.026       0.108
YearRemod-Built           110.0968     58.470      1.883      0.060      -4.595     224.789
ExterQual                1.172e+04   2471.428      4.743      0.000    6873.393    1.66e+04
BsmtQual                 4570.4958   1644.291      2.780      0.006    1345.118    7795.874
BsmtFinType1              917.3079    621.679      1.476      0.140    -302.154    2136.770
BsmtFinSF1                -45.4170    207.169     -0.219      0.827    -451.792     360.958
BsmtFinType1*BsmtFinSF1     4.7345      1.480      3.200      0.001       1.832       7.637
1stFlrSF                    1.3566      4.732      0.287      0.774      -7.925      10.638
HeatingQC                2107.0021   1092.536      1.929      0.054     -36.074    4250.078
BsmtFinType2            -3232.9142   1480.435     -2.184      0.029   -6136.878    -328.950
BsmtFinSF2                -57.9829    206.884     -0.280      0.779    -463.799     347.834
BsmtFinType2*BsmtFinSF2    13.2426      3.445      3.844      0.000       6.485      20.000
BsmtUnfSF                 -42.9755    206.795     -0.208      0.835    -448.616     362.665
TotalBsmtSF*BsmtUnfSF       0.0047      0.004      1.101      0.271      -0.004       0.013
KitchenQual              9776.7261   1941.793      5.035      0.000    5967.780    1.36e+04
BedroomAbvGr            -1.106e+04   2750.348     -4.021      0.000   -1.65e+04   -5664.530
FullBath                -1.866e+04   5023.414     -3.714      0.000   -2.85e+04   -8805.530
BedroomAbvGr*FullBath    7060.3550   1492.747      4.730      0.000    4132.240    9988.470
Fireplaces               2268.4211   2727.965      0.832      0.406   -3082.651    7619.494
FireplaceQu              2154.5224    970.112      2.221      0.027     251.587    4057.458
Hip                      1.109e+04   2214.555      5.010      0.000    6751.003    1.54e+04
Other_roof              -6952.5277   6612.218     -1.051      0.293   -1.99e+04    6017.747
==============================================================================
Omnibus:                      557.210   Durbin-Watson:                   2.074
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            40139.590
Skew:                          -0.801   Prob(JB):                         0.00
Kurtosis:                      27.976   Cond. No.                     4.67e+08
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.67e+08. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [20]:
# prints the linear model evaluation metrics for the train data set using the self-created function
lin_metrics(lm, X_train, y_train)

r2_score = 0.8598959330363204
=====================
cross_val_score = 0.8389346338734576
=====================
RMSE = 30053.663990729197
=====================
MSE = 903222719.2676529
=====================
adj_r2 = 0.8550875162024391

In [21]:
# prints the linear model evaluation metrics for the test data set using the self-created function
lin_metrics(lm, X_test, y_test)

r2_score = 0.8821246609820645
=====================
cross_val_score = 0.8724113993794411
=====================
RMSE = 26088.53827369718
=====================
MSE = 680611829.2581627
=====================
adj_r2 = 0.8690842221753081

## Test Data Set Results

In [22]:
# imports the test.csv dataset 
test_df = pd.read_csv('./data/test.csv') 
test_df.head()

,Id,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type
0,2658,902301120,190,RM,69.0,9142,Pave,Grvl,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,4,2006,WD
1,2718,905108090,90,RL,NaN,9662,Pave,NaN,IR1,Lvl,...,0,0,0,NaN,NaN,NaN,0,8,2006,WD
2,2414,528218130,60,RL,58.0,17104,Pave,NaN,IR1,Lvl,...,0,0,0,NaN,NaN,NaN,0,9,2006,New
3,1989,902207150,30,RM,60.0,8520,Pave,NaN,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,7,2007,WD
4,625,535105100,20,RL,NaN,9500,Pave,NaN,IR1,Lvl,...,0,185,0,NaN,NaN,NaN,0,7,2009,WD

In [23]:
# cleaning function to clean the test.csv dataset and prepare predictions for kaggle
def clean_df (df):
    
    df.columns = df.columns.str.replace(' ', '')
    df['ln_GrLivArea'] = np.log(df['GrLivArea'])
    df['ln_LotArea'] = np.log(df['LotArea'])
    
#     nhood_count = pd.DataFrame(df['Neighborhood'].value_counts(dropna=False))
#     nhood_filter = list(nhood_count[nhood_count['Neighborhood'] < 20].index)
    nhood_filter = ['Blueste', 'Greens', 'GrnHill', 'Landmrk']
    df['Neighborhood'] = np.where(df['Neighborhood'].isin(nhood_filter), 'Other_nhood', df['Neighborhood'])
    nhood_dummies = pd.get_dummies(df['Neighborhood'], drop_first=True)
    df = pd.concat([df, nhood_dummies], axis=1)
    df['GarageArea'].fillna(df['GarageArea'].median(), inplace=True)
    df['TotalBsmtSF'].fillna(df['TotalBsmtSF'].median(), inplace=True)
    df['YearBuilt_squ'] = df['YearBuilt']**2
    df['YearRemod-Built'] = df['YearRemod/Add'] - df['YearBuilt']
    
    df['RoofStyle'] = np.where(df['RoofStyle'].isin(['Flat', 'Gambrel', 'Mansard', 'Shed']), 'Other_roof', df['RoofStyle'])
    roof_dummies = pd.get_dummies(df['RoofStyle'], drop_first=True)
    df = pd.concat([df, roof_dummies], axis=1)
    
    df['ExterQual'] = df['ExterQual'].map({'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5})
    df['BsmtQual'] = df['BsmtQual'].map({np.nan:0, 'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5})
    df['BsmtFinType1'] = df['BsmtFinType1'].map({np.nan:0, 'Unf':1, 'LwQ':2, 'Rec':3, 'BLQ':4, 'ALQ':5, 'GLQ':6})
    df['BsmtFinSF1'].fillna(df['BsmtFinSF1'].median(), inplace=True)
    df['BsmtFinType1*BsmtFinSF1'] = df['BsmtFinType1'] * df['BsmtFinSF1']
    
    df['BsmtFinType2'] = df['BsmtFinType2'].map({np.nan:0, 'Unf':1, 'LwQ':2, 'Rec':3, 'BLQ':4, 'ALQ':5, 'GLQ':6})
    df['BsmtFinSF2'].fillna(df['BsmtFinSF2'].median(), inplace=True)
    df['BsmtFinType2*BsmtFinSF2'] = df['BsmtFinType2'] * df['BsmtFinSF2']
    
    df['ln_1stFlrSF'] = np.log(df['1stFlrSF'])
    df['HeatingQC'] = df['HeatingQC'].map({np.nan:0, 'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5})
    df['CentralAir'] = df['CentralAir'].map({'Y':1, 'N': 0})
    df['HeatingQC*CentralAir'] = df['HeatingQC'] * df['CentralAir']
    
    df['BsmtUnfSF'].fillna(df['BsmtUnfSF'].median(), inplace=True)
    df['TotalBsmtSF*BsmtUnfSF'] = df['TotalBsmtSF'] * df['BsmtUnfSF']
    
    df['KitchenQual'] = df['KitchenQual'].map({np.nan:0, 'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5})
    df['BedroomAbvGr*FullBath'] = df['BedroomAbvGr'] * df['FullBath']
    
    df['FireplaceQu'] = df['FireplaceQu'].map({np.nan:0, 'Po':1, 'Fa':2, 'TA':3, 'Gd':4, 'Ex':5})
    return df

In [24]:
# cleans the test.csv dataset
test_df = clean_df(test_df)

In [25]:
# submission function 
def submission(test_df, model, X):
    
    submission = pd.DataFrame(test_df['Id'])
    submission['SalePrice'] = model.predict(test_df[X.columns])
    submission.to_csv('./data/submissions_final.csv', index=False)
    
    return submission

In [27]:
# saves the submissions to csv and outputs the resulting dataframe
submission(test_df, lm, X)

       Id      SalePrice
0    2658  131150.120958
1    2718  167395.638124
2    2414  231005.098182
3    1989  115024.193464
4     625  167736.799083
..    ...            ...
873  1662  179110.842054
874  1234  223133.168468
875  1373  139726.773631
876  1672  107544.108655
877  1939  121913.679222

[878 rows x 2 columns]